# Generated by Django 4.2.20 on 2025-04-01 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=40)),
                ("username", models.CharField(max_length=40)),
                ("password", models.CharField(max_length=162)),
                ("email", models.EmailField(max_length=60)),
                ("photo_url", models.CharField(default="None", max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=60)),
                ("status", models.CharField(max_length=30)),
                ("expiration", models.DateTimeField(blank=True, null=True)),
                ("timezone", models.CharField(max_length=30)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_groups",
                        to="chore_tracker.user",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="joined_groups", to="chore_tracker.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=60)),
                ("first_date", models.DateField()),
                ("first_time", models.TimeField()),
                (
                    "repeat_every",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="chore_tracker.group",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="events", to="chore_tracker.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cost",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=60)),
                ("category", models.CharField(blank=True, max_length=40, null=True)),
                ("amount", models.FloatField()),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrower",
                        to="chore_tracker.user",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="chore_tracker.group",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="chore_tracker.user",
                    ),
                ),
            ],
        ),
    ]
