# Generated by Django 4.2.20 on 2025-04-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chore_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
